### ISSUE TITLE
List of things todo

### ISSUE THREAD

**Issue by unitoftime** [jstewart7/mmo#35]
- [ ] Client replay buffer gets mucked when you lose focus on window (even when you just alt tab)
- [ ] Optimizations: Minimize data sent over the network
- [ ] Optimizations: Desktop profile all code systems to optimize the big players
- [ ] Interpolation lag: Sometimes you slide into final position, sometimes you slide backwards (high ping)
- [ ] Error gate on client: Reconnect or reload renderer. Maybe force a page refresh if all goes poorly.
